/**
 * ITPS Tariff Data — 135 Countries
 * Source: India Post Revised Tariff and Weight of ITPS
 *
 * Fields:
 *   country  {string}  — Country name
 *   first50  {number}  — Tariff (INR) for first 50g or part thereof
 *   additional {number} — Tariff (INR) for every additional 50g or part thereof
 *   maxWeight {string} — Maximum permissible weight (display string)
 */

const TARIFF_DATA = [
  { country: "Afghanistan",              first50: 285, additional: 50,  maxWeight: "2 kg" },
  { country: "Albania",                  first50: 275, additional: 40,  maxWeight: "2 kg" },
  { country: "Algeria",                  first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Angola",                   first50: 315, additional: 60,  maxWeight: "2 kg" },
  { country: "Argentina",                first50: 360, additional: 65,  maxWeight: "2 kg" },
  { country: "Armenia",                  first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Aruba",                    first50: 220, additional: 50,  maxWeight: "5 kg" },
  { country: "Australia",                first50: 395, additional: 45,  maxWeight: "2 kg" },
  { country: "Austria",                  first50: 325, additional: 30,  maxWeight: "2 kg" },
  { country: "Azerbaijan",               first50: 255, additional: 25,  maxWeight: "2 kg" },
  { country: "Bahrain",                  first50: 290, additional: 20,  maxWeight: "2 kg" },
  { country: "Bangladesh",               first50: 240, additional: 20,  maxWeight: "2 kg" },
  { country: "Belarus",                  first50: 195, additional: 25,  maxWeight: "5 kg" },
  { country: "Belgium",                  first50: 325, additional: 30,  maxWeight: "2 kg" },
  { country: "Benin",                    first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Bhutan",                   first50: 185, additional: 15,  maxWeight: "5 kg" },
  { country: "Bosnia and Herzegovina",   first50: 355, additional: 35,  maxWeight: "2 kg" },
  { country: "Botswana",                 first50: 295, additional: 55,  maxWeight: "2 kg" },
  { country: "Brazil",                   first50: 290, additional: 55,  maxWeight: "2 kg" },
  { country: "Brunei Darussalam",        first50: 260, additional: 30,  maxWeight: "2 kg" },
  { country: "Bulgaria",                 first50: 195, additional: 25,  maxWeight: "5 kg" },
  { country: "Burkina Faso",             first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Burundi",                  first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Cambodia",                 first50: 310, additional: 25,  maxWeight: "2 kg" },
  { country: "Cameroon",                 first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Canada",                   first50: 360, additional: 40,  maxWeight: "2 kg" },
  { country: "Chile",                    first50: 235, additional: 65,  maxWeight: "5 kg" },
  { country: "China",                    first50: 185, additional: 15,  maxWeight: "5 kg" },
  { country: "Colombia",                 first50: 315, additional: 60,  maxWeight: "2 kg" },
  { country: "Costa Rica",               first50: 300, additional: 55,  maxWeight: "2 kg" },
  { country: "Cote d'Ivoire",            first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Croatia",                  first50: 355, additional: 30,  maxWeight: "2 kg" },
  { country: "Curacao",                  first50: 220, additional: 50,  maxWeight: "5 kg" },
  { country: "Cyprus",                   first50: 305, additional: 35,  maxWeight: "2 kg" },
  { country: "Czechia",                  first50: 275, additional: 30,  maxWeight: "2 kg" },
  { country: "Denmark",                  first50: 325, additional: 30,  maxWeight: "2 kg" },
  { country: "Djibouti",                 first50: 290, additional: 45,  maxWeight: "2 kg" },
  { country: "Dominican Republic",       first50: 235, additional: 65,  maxWeight: "5 kg" },
  { country: "Egypt",                    first50: 195, additional: 25,  maxWeight: "5 kg" },
  { country: "Eritrea",                  first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Estonia",                  first50: 220, additional: 25,  maxWeight: "5 kg" },
  { country: "Eswatini",                 first50: 290, additional: 55,  maxWeight: "2 kg" },
  { country: "Ethiopia",                 first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Finland",                  first50: 370, additional: 35,  maxWeight: "2 kg" },
  { country: "France",                   first50: 335, additional: 30,  maxWeight: "2 kg" },
  { country: "Gabon",                    first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Gambia",                   first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Georgia",                  first50: 205, additional: 35,  maxWeight: "2 kg" },
  { country: "Germany",                  first50: 245, additional: 25,  maxWeight: "2 kg" },
  { country: "Ghana",                    first50: 385, additional: 50,  maxWeight: "2 kg" },
  { country: "Gibraltar",                first50: 200, additional: 30,  maxWeight: "5 kg" },
  { country: "Great Britain",            first50: 200, additional: 25,  maxWeight: "5 kg" },
  { country: "Greece",                   first50: 375, additional: 35,  maxWeight: "2 kg" },
  { country: "Hong Kong",                first50: 190, additional: 15,  maxWeight: "5 kg" },
  { country: "Hungary",                  first50: 315, additional: 30,  maxWeight: "2 kg" },
  { country: "Iceland",                  first50: 350, additional: 50,  maxWeight: "2 kg" },
  { country: "Indonesia",                first50: 305, additional: 20,  maxWeight: "2 kg" },
  { country: "Iran (Islamic Republic)",  first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Iraq",                     first50: 285, additional: 45,  maxWeight: "2 kg" },
  { country: "Ireland",                  first50: 320, additional: 35,  maxWeight: "2 kg" },
  { country: "Israel",                   first50: 360, additional: 35,  maxWeight: "2 kg" },
  { country: "Italy",                    first50: 350, additional: 30,  maxWeight: "2 kg" },
  { country: "Japan",                    first50: 310, additional: 20,  maxWeight: "2 kg" },
  { country: "Jersey",                   first50: 210, additional: 25,  maxWeight: "5 kg" },
  { country: "Jordan",                   first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Kazakhstan",               first50: 190, additional: 10,  maxWeight: "5 kg" },
  { country: "Kenya",                    first50: 240, additional: 30,  maxWeight: "2 kg" },
  { country: "Kiribati",                 first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Korea (Republic)",         first50: 310, additional: 20,  maxWeight: "2 kg" },
  { country: "Kuwait",                   first50: 230, additional: 25,  maxWeight: "2 kg" },
  { country: "Kyrgyzstan",               first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Latvia",                   first50: 385, additional: 35,  maxWeight: "2 kg" },
  { country: "Liberia",                  first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Lithuania",                first50: 195, additional: 25,  maxWeight: "5 kg" },
  { country: "Luxembourg",               first50: 320, additional: 30,  maxWeight: "2 kg" },
  { country: "Macao (China)",            first50: 265, additional: 30,  maxWeight: "2 kg" },
  { country: "Malawi",                   first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Malaysia",                 first50: 190, additional: 15,  maxWeight: "5 kg" },
  { country: "Maldives",                 first50: 195, additional: 15,  maxWeight: "2 kg" },
  { country: "Mali",                     first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Malta",                    first50: 340, additional: 35,  maxWeight: "2 kg" },
  { country: "Mauritius",                first50: 295, additional: 35,  maxWeight: "2 kg" },
  { country: "Mexico",                   first50: 220, additional: 50,  maxWeight: "5 kg" },
  { country: "Moldova",                  first50: 290, additional: 60,  maxWeight: "2 kg" },
  { country: "Mongolia",                 first50: 345, additional: 60,  maxWeight: "2 kg" },
  { country: "Montenegro",               first50: 270, additional: 35,  maxWeight: "2 kg" },
  { country: "Morocco",                  first50: 195, additional: 25,  maxWeight: "5 kg" },
  { country: "Mozambique",               first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Myanmar",                  first50: 185, additional: 15,  maxWeight: "5 kg" },
  { country: "Namibia",                  first50: 280, additional: 45,  maxWeight: "2 kg" },
  { country: "Nepal",                    first50: 220, additional: 15,  maxWeight: "2 kg" },
  { country: "Netherlands",              first50: 320, additional: 30,  maxWeight: "2 kg" },
  { country: "New Zealand",              first50: 390, additional: 55,  maxWeight: "2 kg" },
  { country: "Nigeria",                  first50: 250, additional: 45,  maxWeight: "2 kg" },
  { country: "North Macedonia",          first50: 295, additional: 40,  maxWeight: "2 kg" },
  { country: "Norway",                   first50: 325, additional: 35,  maxWeight: "2 kg" },
  { country: "Oman",                     first50: 200, additional: 15,  maxWeight: "5 kg" },
  { country: "Papua New Guinea",         first50: 300, additional: 65,  maxWeight: "2 kg" },
  { country: "Philippines",              first50: 205, additional: 15,  maxWeight: "5 kg" },
  { country: "Poland",                   first50: 355, additional: 30,  maxWeight: "2 kg" },
  { country: "Portugal",                 first50: 305, additional: 35,  maxWeight: "2 kg" },
  { country: "Qatar",                    first50: 385, additional: 25,  maxWeight: "2 kg" },
  { country: "Romania",                  first50: 310, additional: 25,  maxWeight: "2 kg" },
  { country: "Russian Federation",       first50: 245, additional: 30,  maxWeight: "5 kg" },
  { country: "Rwanda",                   first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Saudi Arabia",             first50: 280, additional: 25,  maxWeight: "2 kg" },
  { country: "Senegal",                  first50: 275, additional: 45,  maxWeight: "2 kg" },
  { country: "Serbia",                   first50: 325, additional: 30,  maxWeight: "2 kg" },
  { country: "Sierra Leone",             first50: 295, additional: 45,  maxWeight: "2 kg" },
  { country: "Singapore",                first50: 185, additional: 15,  maxWeight: "5 kg" },
  { country: "Slovakia",                 first50: 300, additional: 30,  maxWeight: "2 kg" },
  { country: "Slovenia",                 first50: 260, additional: 30,  maxWeight: "2 kg" },
  { country: "Solomon Island",           first50: 220, additional: 45,  maxWeight: "5 kg" },
  { country: "South Africa",             first50: 245, additional: 35,  maxWeight: "2 kg" },
  { country: "Spain",                    first50: 295, additional: 35,  maxWeight: "2 kg" },
  { country: "Sri Lanka",                first50: 305, additional: 15,  maxWeight: "2 kg" },
  { country: "Sweden",                   first50: 320, additional: 30,  maxWeight: "2 kg" },
  { country: "Switzerland",              first50: 350, additional: 35,  maxWeight: "2 kg" },
  { country: "Tajikistan",               first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Tanzania (United Republic)", first50: 300, additional: 55, maxWeight: "2 kg" },
  { country: "Thailand",                 first50: 185, additional: 10,  maxWeight: "5 kg" },
  { country: "Togo",                     first50: 280, additional: 45,  maxWeight: "2 kg" },
  { country: "Tunisia",                  first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Türkiye",                  first50: 370, additional: 35,  maxWeight: "2 kg" },
  { country: "Turkmenistan",             first50: 300, additional: 50,  maxWeight: "2 kg" },
  { country: "Tuvalu",                   first50: 235, additional: 65,  maxWeight: "5 kg" },
  { country: "Uganda",                   first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Ukraine",                  first50: 195, additional: 20,  maxWeight: "2 kg" },
  { country: "United Arab Emirates",     first50: 185, additional: 15,  maxWeight: "5 kg" },
  { country: "United States of America", first50: 400, additional: 35,  maxWeight: "5 kg" },
  { country: "Uruguay",                  first50: 230, additional: 60,  maxWeight: "5 kg" },
  { country: "Uzbekistan",               first50: 280, additional: 50,  maxWeight: "2 kg" },
  { country: "Vietnam",                  first50: 190, additional: 20,  maxWeight: "5 kg" },
  { country: "Zambia",                   first50: 285, additional: 55,  maxWeight: "2 kg" },
  { country: "Zimbabwe",                 first50: 225, additional: 55,  maxWeight: "5 kg" },
];
